### ISSUE TITLE
download the latest package

### ISSUE THREAD

**Issue by badr-bzh** [cisco-system-traffic-generator/trex-emu#3]
Hello,
I wanted to do the emu test with a proxy (5.3. Proxy > 5.3.1. Intro)
I had this error:
`root@t-rex1:/home/trex-emu-2.84/scripts# go install cmd-proxy/trex-emu-proxy.go
stat cmd-proxy/trex-emu-proxy.go: no such file or directory
`
Is there a way to download the pre built package without building from source ?

**Comment by bdollma** [comment]
Hi, 
There is. The pre built package is part of the TRex image, which can be downloaded here: https://trex-tgn.cisco.com/trex/release/
It is located in the **trex-emu/** dir.
However pay attention that the pre built image support only x86_64.
Thanks,
Bes

**Comment by bdollma** [comment]
Hi, 
The simple answer is no, the proxy is not provided as pre built. The reason is that proxy users usually need to debug stuff, hence should be able to compile on their own. 
Probably the reason why you failed, is that because you are trying to install from the **scripts** directory instead of the **src** directory which should be your **GOPATH**.
I suggest you try once again, cause if you can build the emu package, you should be able to easily build the proxy package again.
For building emu:
Navigate to **scripts** and use `./utility_script build`
For building proxy:
Navigate to **src** and run `go install cmd-proxy/trex-emu-proxy.go`
Lastly, if you don't succeed, let us know and I will send you a pre built package for x86_x64.

**Comment by badr-bzh** [comment]
Thanks you !!
I have this error: 
`root@t-rex1:/home/trex-emu-2.84/scripts# ./utility_script build
go: github.com/akamensky/argparse@v1.2.0: Get "https://proxy.golang.org/github.com/akamensky/argparse/@v/v1.2.0.mod": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:44607->[::1]:53: read: connection refused
`
Do you have any idea ?
Thnaks !

**Comment by badr-bzh** [comment]
I think a proxy is blocking the connectionn is there any way to hack this ?

Thanks!

Badr

**Comment by badr-bzh** [comment]
Or is it possible to provide the pre built package ?

Thanks you,

Badr

**Comment by bdollma** [comment]
Hi, 
Indeed seems like your DNS query is being blocked. Are you by any chance behind a corporate proxy? The problems you are having are not really related to TRex, it is more of a Golang problem. Try to figure out how to set up the **go get** command with the proxy. https://stackoverflow.com/questions/10383299/how-do-i-configure-go-command-to-use-a-proxy

Regarding the pre built package, I hope you can download it without any problems:
https://drive.google.com/file/d/1eEtwArCjqk_ouvP3pdlm3rndOZFJWsFD/view?usp=sharing

**Comment by bdollma** [comment]
@hhaim Can you close this as @badr-bzh hasn't answered in 3 weeks?
Thanks,
